// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1uCgZvm8waHfy_2CXmcUOwG9vSaEiTEU',
    appId: '1:154586994972:web:5e16131b9b2424959c02d9',
    messagingSenderId: '154586994972',
    projectId: 'gessports-eb9e3',
    authDomain: 'gessports-eb9e3.firebaseapp.com',
    storageBucket: 'gessports-eb9e3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWCmX9eQ6PhRd_fVzvGwVJguJN57TY4vo',
    appId: '1:154586994972:android:ce65a4d294fc08ae9c02d9',
    messagingSenderId: '154586994972',
    projectId: 'gessports-eb9e3',
    storageBucket: 'gessports-eb9e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVnmj0vD6ZIV_GGEpqblPD6nBeCXHu3lo',
    appId: '1:154586994972:ios:87f546b1cbecd9549c02d9',
    messagingSenderId: '154586994972',
    projectId: 'gessports-eb9e3',
    storageBucket: 'gessports-eb9e3.firebasestorage.app',
    iosBundleId: 'com.example.loginFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVnmj0vD6ZIV_GGEpqblPD6nBeCXHu3lo',
    appId: '1:154586994972:ios:87f546b1cbecd9549c02d9',
    messagingSenderId: '154586994972',
    projectId: 'gessports-eb9e3',
    storageBucket: 'gessports-eb9e3.firebasestorage.app',
    iosBundleId: 'com.example.loginFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1uCgZvm8waHfy_2CXmcUOwG9vSaEiTEU',
    appId: '1:154586994972:web:b8755dc9f5a22a859c02d9',
    messagingSenderId: '154586994972',
    projectId: 'gessports-eb9e3',
    authDomain: 'gessports-eb9e3.firebaseapp.com',
    storageBucket: 'gessports-eb9e3.firebasestorage.app',
  );
}
